//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class EnvironmentTagMsg : Message
    {
        public const string k_RosMessageName = "maes_interface/EnvironmentTag";
        public override string RosMessageName => k_RosMessageName;

        public double distance;
        public float angle;
        public string content;

        public EnvironmentTagMsg()
        {
            this.distance = 0.0;
            this.angle = 0.0f;
            this.content = "";
        }

        public EnvironmentTagMsg(double distance, float angle, string content)
        {
            this.distance = distance;
            this.angle = angle;
            this.content = content;
        }

        public static EnvironmentTagMsg Deserialize(MessageDeserializer deserializer) => new EnvironmentTagMsg(deserializer);

        private EnvironmentTagMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance);
            deserializer.Read(out this.angle);
            deserializer.Read(out this.content);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance);
            serializer.Write(this.angle);
            serializer.Write(this.content);
        }

        public override string ToString()
        {
            return "EnvironmentTagMsg: " +
            "\ndistance: " + distance.ToString() +
            "\nangle: " + angle.ToString() +
            "\ncontent: " + content.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
