//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class RobotStateMsg : Message
    {
        public const string k_RosMessageName = "maes_interface/RobotState";
        public override string RosMessageName => k_RosMessageName;

        public RobotPosMsg pos;
        public string status;
        public SlamTileMsg[] new_slam_tiles;
        public bool has_collided;
        public RobotMsgMsg[] brdcst_msgs;
        public EnvironmentTagMsg[] env_tags;
        public NearbyRobotMsg[] nearby_robots;

        public RobotStateMsg()
        {
            this.pos = new RobotPosMsg();
            this.status = "";
            this.new_slam_tiles = new SlamTileMsg[0];
            this.has_collided = false;
            this.brdcst_msgs = new RobotMsgMsg[0];
            this.env_tags = new EnvironmentTagMsg[0];
            this.nearby_robots = new NearbyRobotMsg[0];
        }

        public RobotStateMsg(RobotPosMsg pos, string status, SlamTileMsg[] new_slam_tiles, bool has_collided, RobotMsgMsg[] brdcst_msgs, EnvironmentTagMsg[] env_tags, NearbyRobotMsg[] nearby_robots)
        {
            this.pos = pos;
            this.status = status;
            this.new_slam_tiles = new_slam_tiles;
            this.has_collided = has_collided;
            this.brdcst_msgs = brdcst_msgs;
            this.env_tags = env_tags;
            this.nearby_robots = nearby_robots;
        }

        public static RobotStateMsg Deserialize(MessageDeserializer deserializer) => new RobotStateMsg(deserializer);

        private RobotStateMsg(MessageDeserializer deserializer)
        {
            this.pos = RobotPosMsg.Deserialize(deserializer);
            deserializer.Read(out this.status);
            deserializer.Read(out this.new_slam_tiles, SlamTileMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.has_collided);
            deserializer.Read(out this.brdcst_msgs, RobotMsgMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.env_tags, EnvironmentTagMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.nearby_robots, NearbyRobotMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.status);
            serializer.WriteLength(this.new_slam_tiles);
            serializer.Write(this.new_slam_tiles);
            serializer.Write(this.has_collided);
            serializer.WriteLength(this.brdcst_msgs);
            serializer.Write(this.brdcst_msgs);
            serializer.WriteLength(this.env_tags);
            serializer.Write(this.env_tags);
            serializer.WriteLength(this.nearby_robots);
            serializer.Write(this.nearby_robots);
        }

        public override string ToString()
        {
            return "RobotStateMsg: " +
            "\npos: " + pos.ToString() +
            "\nstatus: " + status.ToString() +
            "\nnew_slam_tiles: " + System.String.Join(", ", new_slam_tiles.ToList()) +
            "\nhas_collided: " + has_collided.ToString() +
            "\nbrdcst_msgs: " + System.String.Join(", ", brdcst_msgs.ToList()) +
            "\nenv_tags: " + System.String.Join(", ", env_tags.ToList()) +
            "\nnearby_robots: " + System.String.Join(", ", nearby_robots.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
