//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class SlamTileMsg : Message
    {
        public const string k_RosMessageName = "maes_interface/SlamTile";
        public override string RosMessageName => k_RosMessageName;

        public Vector2DMsg position;
        public bool is_obstacle;

        public SlamTileMsg()
        {
            this.position = new Vector2DMsg();
            this.is_obstacle = false;
        }

        public SlamTileMsg(Vector2DMsg position, bool is_obstacle)
        {
            this.position = position;
            this.is_obstacle = is_obstacle;
        }

        public static SlamTileMsg Deserialize(MessageDeserializer deserializer) => new SlamTileMsg(deserializer);

        private SlamTileMsg(MessageDeserializer deserializer)
        {
            this.position = Vector2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.is_obstacle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.is_obstacle);
        }

        public override string ToString()
        {
            return "SlamTileMsg: " +
            "\nposition: " + position.ToString() +
            "\nis_obstacle: " + is_obstacle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
