//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class BroadcastToAllResponse : Message
    {
        public const string k_RosMessageName = "maes_msgs/BroadcastToAll";
        public override string RosMessageName => k_RosMessageName;

        public bool result;

        public BroadcastToAllResponse()
        {
            this.result = false;
        }

        public BroadcastToAllResponse(bool result)
        {
            this.result = result;
        }

        public static BroadcastToAllResponse Deserialize(MessageDeserializer deserializer) => new BroadcastToAllResponse(deserializer);

        private BroadcastToAllResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "BroadcastToAllResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
