//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class BroadcastToAllRequest : Message
    {
        public const string k_RosMessageName = "maes_msgs/BroadcastToAll";
        public override string RosMessageName => k_RosMessageName;

        public string msg;

        public BroadcastToAllRequest()
        {
            this.msg = "";
        }

        public BroadcastToAllRequest(string msg)
        {
            this.msg = msg;
        }

        public static BroadcastToAllRequest Deserialize(MessageDeserializer deserializer) => new BroadcastToAllRequest(deserializer);

        private BroadcastToAllRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
        }

        public override string ToString()
        {
            return "BroadcastToAllRequest: " +
            "\nmsg: " + msg.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
