//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class DepositTagResponse : Message
    {
        public const string k_RosMessageName = "maes_msgs/DepositTag";
        public override string RosMessageName => k_RosMessageName;

        public bool result;

        public DepositTagResponse()
        {
            this.result = false;
        }

        public DepositTagResponse(bool result)
        {
            this.result = result;
        }

        public static DepositTagResponse Deserialize(MessageDeserializer deserializer) => new DepositTagResponse(deserializer);

        private DepositTagResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "DepositTagResponse: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
