# This config contains only the absolutely necessary fields.
# Open maes_config_complete to find a file containing all possible fields.
number_of_robots: 2
robot_constraints:
   slam_raytrace_range: 10.0
   agent_relative_size: 0.6 # Value in ]0.0-1.0] relative to a tile in the maes generated maps
map:
  width_in_tiles: 50
  height_in_tiles: 50