//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class BroadcastMsg : Message
    {
        public const string k_RosMessageName = "maes_msgs/Broadcast";
        public override string RosMessageName => k_RosMessageName;

        public string msg;
        public string sender;

        public BroadcastMsg()
        {
            this.msg = "";
            this.sender = "";
        }

        public BroadcastMsg(string msg, string sender)
        {
            this.msg = msg;
            this.sender = sender;
        }

        public static BroadcastMsg Deserialize(MessageDeserializer deserializer) => new BroadcastMsg(deserializer);

        private BroadcastMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
            deserializer.Read(out this.sender);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
            serializer.Write(this.sender);
        }

        public override string ToString()
        {
            return "BroadcastMsg: " +
            "\nmsg: " + msg.ToString() +
            "\nsender: " + sender.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
