//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class DepositTag_ResponseMsg : Message
    {
        public const string k_RosMessageName = "maes_msgs/DepositTag_Response";
        public override string RosMessageName => k_RosMessageName;

        public bool result;

        public DepositTag_ResponseMsg()
        {
            this.result = false;
        }

        public DepositTag_ResponseMsg(bool result)
        {
            this.result = result;
        }

        public static DepositTag_ResponseMsg Deserialize(MessageDeserializer deserializer) => new DepositTag_ResponseMsg(deserializer);

        private DepositTag_ResponseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.result);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "DepositTag_ResponseMsg: " +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
