//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class EnvironmentTagMsg : Message
    {
        public const string k_RosMessageName = "maes_msgs/EnvironmentTag";
        public override string RosMessageName => k_RosMessageName;

        public string msg;
        public Vector2DMsg pos;

        public EnvironmentTagMsg()
        {
            this.msg = "";
            this.pos = new Vector2DMsg();
        }

        public EnvironmentTagMsg(string msg, Vector2DMsg pos)
        {
            this.msg = msg;
            this.pos = pos;
        }

        public static EnvironmentTagMsg Deserialize(MessageDeserializer deserializer) => new EnvironmentTagMsg(deserializer);

        private EnvironmentTagMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.msg);
            this.pos = Vector2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.msg);
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "EnvironmentTagMsg: " +
            "\nmsg: " + msg.ToString() +
            "\npos: " + pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
