//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Maes
{
    [Serializable]
    public class NearbyRobotMsg : Message
    {
        public const string k_RosMessageName = "maes_msgs/NearbyRobot";
        public override string RosMessageName => k_RosMessageName;

        public string id;
        public Vector2DMsg pos;

        public NearbyRobotMsg()
        {
            this.id = "";
            this.pos = new Vector2DMsg();
        }

        public NearbyRobotMsg(string id, Vector2DMsg pos)
        {
            this.id = id;
            this.pos = pos;
        }

        public static NearbyRobotMsg Deserialize(MessageDeserializer deserializer) => new NearbyRobotMsg(deserializer);

        private NearbyRobotMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            this.pos = Vector2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "NearbyRobotMsg: " +
            "\nid: " + id.ToString() +
            "\npos: " + pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
