//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class BroadcastResponse : Message
    {
        public const string k_RosMessageName = "maes_interface/Broadcast";
        public override string RosMessageName => k_RosMessageName;

        public string success_status;

        public BroadcastResponse()
        {
            this.success_status = "";
        }

        public BroadcastResponse(string success_status)
        {
            this.success_status = success_status;
        }

        public static BroadcastResponse Deserialize(MessageDeserializer deserializer) => new BroadcastResponse(deserializer);

        private BroadcastResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success_status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success_status);
        }

        public override string ToString()
        {
            return "BroadcastResponse: " +
            "\nsuccess_status: " + success_status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
