//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class MoveGoal : Message
    {
        public const string k_RosMessageName = "maes_interface/Move";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public double distance;

        public MoveGoal()
        {
            this.distance = 0.0;
        }

        public MoveGoal(double distance)
        {
            this.distance = distance;
        }

        public static MoveGoal Deserialize(MessageDeserializer deserializer) => new MoveGoal(deserializer);

        private MoveGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.distance);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.distance);
        }

        public override string ToString()
        {
            return "MoveGoal: " +
            "\ndistance: " + distance.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
