//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class MoveFeedback : Message
    {
        public const string k_RosMessageName = "maes_interface/Move";
        public override string RosMessageName => k_RosMessageName;

        //  Feedback
        public double remaining;

        public MoveFeedback()
        {
            this.remaining = 0.0;
        }

        public MoveFeedback(double remaining)
        {
            this.remaining = remaining;
        }

        public static MoveFeedback Deserialize(MessageDeserializer deserializer) => new MoveFeedback(deserializer);

        private MoveFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.remaining);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.remaining);
        }

        public override string ToString()
        {
            return "MoveFeedback: " +
            "\nremaining: " + remaining.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
