//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class MoveResult : Message
    {
        public const string k_RosMessageName = "maes_interface/Move";
        public override string RosMessageName => k_RosMessageName;

        //  Result
        public Vector2DMsg new_pos;

        public MoveResult()
        {
            this.new_pos = new Vector2DMsg();
        }

        public MoveResult(Vector2DMsg new_pos)
        {
            this.new_pos = new_pos;
        }

        public static MoveResult Deserialize(MessageDeserializer deserializer) => new MoveResult(deserializer);

        private MoveResult(MessageDeserializer deserializer)
        {
            this.new_pos = Vector2DMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.new_pos);
        }

        public override string ToString()
        {
            return "MoveResult: " +
            "\nnew_pos: " + new_pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
