//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class RotateResult : Message
    {
        public const string k_RosMessageName = "maes_interface/Rotate";
        public override string RosMessageName => k_RosMessageName;

        //  Result
        public bool done;

        public RotateResult()
        {
            this.done = false;
        }

        public RotateResult(bool done)
        {
            this.done = done;
        }

        public static RotateResult Deserialize(MessageDeserializer deserializer) => new RotateResult(deserializer);

        private RotateResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.done);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.done);
        }

        public override string ToString()
        {
            return "RotateResult: " +
            "\ndone: " + done.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
