//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MaesInterface
{
    [Serializable]
    public class RotateGoal : Message
    {
        public const string k_RosMessageName = "maes_interface/Rotate";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public float degrees;

        public RotateGoal()
        {
            this.degrees = 0.0f;
        }

        public RotateGoal(float degrees)
        {
            this.degrees = degrees;
        }

        public static RotateGoal Deserialize(MessageDeserializer deserializer) => new RotateGoal(deserializer);

        private RotateGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.degrees);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.degrees);
        }

        public override string ToString()
        {
            return "RotateGoal: " +
            "\ndegrees: " + degrees.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
